title: Sistemes de Gestió Empresarial - IES Benigasló
description: Módul de 2º de cicles de grau superior DAM i DAW
theme: just-the-docs

url: https://gasensios.github.io/SGE_Documentacion/


aux_links:
  "Accés a Aules": 
    - https://aules.edu.gva.es/fp/

search_enabled: true

footer:
  copyright: "© 2024 El Meu Projecte"
  links:
    - title: "Llicència CC BY-SA 4.0"
      url: "https://creativecommons.org/licenses/by-sa/4.0/"

# Navegació directa sense desplegables
collections:
  docs:
    output: true
    permalink: /:path/